language: python
cache: pip
dist: xenial

matrix:
  include:
  - env: TOXENV=py37-dj111-wt2
    python: 3.7
  - env: TOXENV=py37-dj2-wt21
    python: 3.7
  - env: TOXENV=py37-dj2-wt22
    python: 3.7
  - env: TOXENV=py37-dj2-wt23
    python: 3.7
  - env: TOXENV=py37-dj2-wt24
    python: 3.7
  - env: TOXENV=py37-dj22-wt25
    python: 3.7
  - env: TOXENV=py37-dj22-wt26
    python: 3.7
  - env: TOXENV=py38-dj22-wt27
    python: 3.8
  - env: TOXENV=py38-dj3-wt28
    python: 3.8
  - env: TOXENV=py38-dj3-wt29
    python: 3.8
  - env: TOXENV=py38-dj3-wt210
    python: 3.8

install:
- pip install tox codecov

script:
- tox

after_success:
- codecov

deploy:
  provider: pypi
  user: ${PYPI_USER}
  distributions: sdist bdist_wheel
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    branch: master
    repo: rkhleics/wagtailmenus
    condition: "$TOXENV=py38-dj22-wt27"
