language: python
cache: pip
dist: trusty
sudo: required

matrix:
  include:
  - env: TOXENV=py27-dj18-wt15
    python: 2.7
  - env: TOXENV=py33-dj18-wt15
    python: 3.3
  - env: TOXENV=py35-dj19-wt15
    python: 3.5  
  - env: TOXENV=py35-dj110-wt16
    python: 3.5
  - env: TOXENV=py35-dj110-wt17
    python: 3.5 
  - env: TOXENV=py35-dj110-wt18
    python: 3.5 
  - env: TOXENV=py36-dj110-wt19
    python: 3.6 
  - env: TOXENV=py36-dj111-wt110
    python: 3.6 
  - env: TOXENV=py36-dj111-wt111
    python: 3.6 

install:
- pip install tox codecov

script:
- tox

after_success: 
- codecov
