language: python
cache: pip
sudo: false
matrix:
  include:
  - env: TOXENV=py27-dj18-wt15
    python: 2.7
  - env: TOXENV=py33-dj18-wt15
    python: 3.3
  - env: TOXENV=py34-dj18-wt15
    python: 3.4
  - env: TOXENV=py35-dj18-wt15
    python: 3.5
  - env: TOXENV=py35-dj19-wt15
    python: 3.5  
  - env: TOXENV=py35-dj110-wt16
    python: 3.5
  - env: TOXENV=py35-dj110-wt17
    python: 3.5 
  - env: TOXENV=py35-dj110-wt18
    python: 3.5  
install:
- pip install tox coveralls
script:
- tox
after_success: coveralls
